context:
  version: "1.26.4"
  target: "x86_64-pc-freebsd14.4"
  sysroot: ${{ env.SYSROOT | default("/opt/freebsd-sysroot/x86_64-pc-freebsd14.4") }}

package:
  name: numpy
  version: ${{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v${{ version }}/numpy-${{ version }}.tar.gz

build:
  number: 0
  dynamic_linking:
    binary_relocation: false
  script:
    - export CC="clang -target ${{ target }} --sysroot=${{ sysroot }} -fPIC"
    - export CXX="clang++ -target ${{ target }} --sysroot=${{ sysroot }} -fPIC"
    - export AR="llvm-ar"
    - export LD="ld.lld"
    - export RANLIB="llvm-ranlib"
    - export PKG_CONFIG_LIBDIR=$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig
    - export PKG_CONFIG_PATH=""
    - >
      python -m pip install .
      --no-deps
      --no-build-isolation
      --ignore-installed
      -v
      --prefix=$PREFIX

requirements:
  build:
    - python
    - pip
    - wheel
    - meson-python
    - cython
    - pkg-config
  host:
    - python
    - openblas
  run:
    - python
    - openblas

about:
  homepage: https://www.numpy.org
  license: BSD-3-Clause
  summary: Fundamental package for scientific computing with Python (freebsd-64 cross-compiled)
